import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface PdfReportSection {
  heading: string;
  subLabel?: string;
  columns: string[];
  /** Each row is an array of cell strings matching columns order. Row number is prepended automatically. */
  rows: string[][];
}

export interface PdfReportData {
  title: string;
  subtitle?: string;
  dateRange?: string;
  groupedBy?: string;
  filters?: string;
  generatedBy: string;
  generatedByRole: string;
  sections: PdfReportSection[];
  grandTotalLabel: string;
}

// ─── Colors ─────────────────────────────────────────────────────────────────

const GREEN = { r: 26, g: 86, b: 50 } as const;         // #1a5632
const GREEN_LIGHT = { r: 232, g: 240, b: 235 } as const; // #e8f0eb
const BLUE = { r: 26, g: 74, b: 107 } as const;          // #1a4a6b
const AMBER = { r: 107, g: 90, b: 26 } as const;         // #6b5a1a
const GRAY_50 = { r: 249, g: 250, b: 251 } as const;     // #f9fafb
const GRAY_600 = { r: 75, g: 85, b: 99 } as const;
const GRAY_900 = { r: 17, g: 24, b: 39 } as const;

const GROUP_COLORS = [GREEN, BLUE, AMBER];

// ─── Main Generator ─────────────────────────────────────────────────────────

export async function generateReportPdf(data: PdfReportData): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = { left: 14, right: 14, top: 10 };
  const contentWidth = pageWidth - margin.left - margin.right;

  const now = new Date();
  const generatedOn = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const generatedTime = now.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });

  // ── Helper: add footer to every page ──
  const addFooters = () => {
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      const footerY = pageHeight - 10;

      // Top line
      doc.setDrawColor(GREEN.r, GREEN.g, GREEN.b);
      doc.setLineWidth(0.6);
      doc.line(margin.left, footerY - 3, pageWidth - margin.right, footerY - 3);

      // Left side
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(GRAY_900.r, GRAY_900.g, GRAY_900.b);
      doc.text("City of Cabanatuan", margin.left, footerY);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
      doc.text("Province of Nueva Ecija", margin.left, footerY + 3);

      // Right side
      doc.setFontSize(7);
      doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
      doc.text(
        `Date Printed: ${generatedOn}   Time Printed: ${generatedTime}`,
        pageWidth - margin.right,
        footerY,
        { align: "right" },
      );
      doc.text(
        `Page ${i} of ${totalPages}  ·  Generated by: Cabanatuan City Ordinance Portal`,
        pageWidth - margin.right,
        footerY + 3,
        { align: "right" },
      );
    }
  };

  // ── Header ──
  let y = margin.top;

  // Metadata (top right)
  doc.setFontSize(7);
  doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
  doc.setFont("helvetica", "normal");
  const metaLines: string[] = [];
  if (data.dateRange) metaLines.push(`Date Range: ${data.dateRange}`);
  if (data.groupedBy) metaLines.push(`Grouped By: ${data.groupedBy}`);
  if (data.filters) metaLines.push(`Filters: ${data.filters}`);
  metaLines.push(`Generated On: ${generatedOn} at ${generatedTime}`);
  metaLines.forEach((line, i) => {
    doc.text(line, pageWidth - margin.right, y + 3 + i * 3.5, {
      align: "right",
    });
  });

  y += metaLines.length * 3.5 + 4;

  // Center header text
  const centerX = pageWidth / 2;
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
  doc.text("REPUBLIC OF THE PHILIPPINES", centerX, y + 2, { align: "center" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(GREEN.r, GREEN.g, GREEN.b);
  doc.text("City of Cabanatuan", centerX, y + 8, { align: "center" });

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
  doc.text("Province of Nueva Ecija", centerX, y + 12, { align: "center" });

  y += 17;

  // Header bottom line
  doc.setDrawColor(GREEN.r, GREEN.g, GREEN.b);
  doc.setLineWidth(1);
  doc.line(margin.left, y, pageWidth - margin.right, y);
  y += 8;

  // ── Title ──
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(GRAY_900.r, GRAY_900.g, GRAY_900.b);
  doc.text(data.title, centerX, y, { align: "center" });
  y += 3;
  if (data.subtitle) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
    doc.text(data.subtitle, centerX, y + 2, { align: "center" });
    y += 5;
  }
  y += 5;

  // ── Sections (tables) ──
  let totalRows = 0;

  data.sections.forEach((section, sectionIdx) => {
    const groupColor = GROUP_COLORS[sectionIdx % GROUP_COLORS.length];

    // Check if we have enough space for heading + at least a few rows
    if (y > pageHeight - 50) {
      doc.addPage();
      y = margin.top + 5;
    }

    // Group heading bar
    const headingHeight = section.subLabel ? 9 : 7;
    doc.setFillColor(groupColor.r, groupColor.g, groupColor.b);
    doc.roundedRect(margin.left, y, contentWidth, headingHeight, 1, 1, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(section.heading, margin.left + 3, y + 5);
    if (section.subLabel) {
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "normal");
      doc.text(section.subLabel, margin.left + 3, y + 8);
    }
    y += headingHeight + 1;

    // Table
    const numberedRows = section.rows.map((row, i) => [
      String(i + 1),
      ...row,
    ]);

    autoTable(doc, {
      startY: y,
      head: [["#", ...section.columns]],
      body: numberedRows,
      margin: { left: margin.left, right: margin.right },
      theme: "grid",
      styles: {
        fontSize: 7,
        cellPadding: 1.5,
        lineColor: [200, 200, 200],
        lineWidth: 0.2,
        textColor: [GRAY_900.r, GRAY_900.g, GRAY_900.b],
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: [GREEN_LIGHT.r, GREEN_LIGHT.g, GREEN_LIGHT.b],
        textColor: [GRAY_900.r, GRAY_900.g, GRAY_900.b],
        fontStyle: "bold",
        fontSize: 7,
      },
      alternateRowStyles: {
        fillColor: [GRAY_50.r, GRAY_50.g, GRAY_50.b],
      },
      columnStyles: {
        0: { cellWidth: 8, halign: "center" },
        1: { cellWidth: 26 }, // Ensure Resolution No. has enough space
      },
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 1;

    // Subtotal line
    doc.setFontSize(7);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
    doc.text(
      `Subtotal (${section.heading}): ${section.rows.length}`,
      pageWidth - margin.right,
      y + 2,
      { align: "right" },
    );
    y += 6;

    totalRows += section.rows.length;
  });

  // ── Grand Total ──
  if (y > pageHeight - 40) {
    doc.addPage();
    y = margin.top + 5;
  }

  doc.setDrawColor(GRAY_900.r, GRAY_900.g, GRAY_900.b);
  doc.setLineWidth(0.5);
  // Full width line for grand total
  doc.line(margin.left, y, pageWidth - margin.right, y);
  y += 5;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(GRAY_900.r, GRAY_900.g, GRAY_900.b);
  doc.text(data.grandTotalLabel, centerX, y, { align: "center" });
  y += 10;

  // ── Prepared By ──
  if (y > pageHeight - 40) {
    doc.addPage();
    y = margin.top + 5;
  }

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GRAY_600.r, GRAY_600.g, GRAY_600.b);
  doc.text("Prepared by:", margin.left, y);
  y += 20; // Increased spacing for signature

  // Signature line
  doc.setDrawColor(GRAY_900.r, GRAY_900.g, GRAY_900.b);
  doc.setLineWidth(0.3);
  doc.line(margin.left, y, margin.left + 65, y);

  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(150, 150, 150);
  doc.text("Signature over printed name", margin.left, y + 4);

  // ── Add footers to all pages ──
  addFooters();

  // ── Save ──
  const filename = data.title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
  doc.save(`${filename}-${generatedOn.replace(/,?\s+/g, "-").toLowerCase()}.pdf`);
}
